- index.d.ts
- package.json
- add type definition for node-sql-parser
> add type definition

- .eslintrc
- DONATIONLIST.md
- lib/sql.js
- package.json
- sql.pegjs
- test/ast.spec.js
- test/cmd.spec.js
- test/insert.spec.js
- support basic alter: add a column , drop column
- support set variables
- update donation list
> Feature alter

- lib/sql.js
- sql.pegjs
- test/ast.spec.js
- test/cmd.spec.js
- alter table add index syntax feature
> Feature alter index

- index.d.ts
- package.json
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/func.js
- test/ast.spec.js
- support pg cast
- fix `index.d.ts` error
> Feature colon cast

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/create.spec.js
- fix `create table` syntax with constraints bug
> Bug create table

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/create.spec.js
> Feature charset

- index.d.ts
I add type use in declare file
> Add interface Use

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/select.js
- src/util.js
- test/ast.spec.js
- test/select.spec.js
- support mysql limit and offset
- support pg limit all
> support pg limit

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/util.js
- test/ast.spec.js
> do not escape in sigle quote

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/command.js
- src/sql.js
- src/union.js
- test/cmd.spec.js
- support lock and unlock for mysql and maridb
- support lock for pg
> support lock and unlock

- README.md
- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/postgresql.pegjs
- src/insert.js
- src/parser.js
- test/ast.spec.js
- test/insert.spec.js
- add hive support
- MySQL insert no columns support
> add hive sql support

- package.json
- pegjs/hive.pegjs
- fix hive table keyword could be optional bug
> add table to optional

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/alter.js
- src/insert.js
- test/cmd.spec.js
- test/insert.spec.js
- support alter table rename
- support insert partition
> support alter table rename and insert partition

- package.json
- pegjs/postgresql.pegjs
- src/util.js
- test/select.spec.js
- support pg json property query
> support pg json column

- package.json
- pegjs/mysql.pegjs
- src/aggregation.js
- test/select.spec.js
> Feature select over

- package.json
- pegjs/mysql.pegjs
- src/aggregation.js
- src/func.js
- test/select.spec.js
> support funcion parition by

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/insert.spec.js
- support ctrl char(0-31 and 127) in ASCII, \0-\x1f\7f in values
> Feature ascii ctrl

- package.json
- pegjs/mysql.pegjs
- src/aggregation.js
- src/expr.js
- src/func.js
- src/over.js
- src/select.js
- test/ast.spec.js
- test/select.spec.js
- support `order by` followed by `partition by`
> support over partition by with order by

- pegjs/mysql.pegjs
> Added support for TINYINT

- pegjs/mysql.pegjs
- test/select.spec.js
> support group by column index

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/interval.js
- test/ast.spec.js
> Feature interval expr

- README.md
- package.json
- pegjs/mysql.pegjs
- pegjs/transactsql.pegjs
- src/parser.js
- src/util.js
- test/ast.spec.js
- test/select.spec.js
> Feature remove column name check

- package.json
- pegjs/transactsql.pegjs
- src/select.js
- src/util.js
- test/select.spec.js
- support top n [percent] in transact sql grammar
> support top n in transact sql

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
- remove user as keyword
- scalar function must have parentheses
- related issue #215
> remove user keyword, scalar funtion must have parentheses

- package.json
- pegjs/mysql.pegjs
- remove status keyword
- related issue #216
> remove status keyword

- pegjs/mysql.pegjs
- test/create.spec.js
> Support BIGINT fields

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/create.spec.js
> Feature default current timestamp

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/alter.js
- test/cmd.spec.js
- support alter grammar with `algorithm` and `lock` setting
- fix #231
> add alter algorithm and lock setting

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/constrain.js
- test/create.spec.js
- #233 
- support unsigned and zerofill
> support unsigned and zerofill for create table syntax

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/func.js
- test/create.spec.js
- test/select.spec.js
- support feature #238 
- fix issue #241
> Feature decimal json

- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/create.spec.js
- support #257 
- support float and double field type
> support float and double

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/ast.spec.js
> support pg cast by literal

- .github/ISSUE_TEMPLATE/node-sql-parser-bug-report.md
> Update issue templates

- package-lock.json
- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/union.js
- test/ast.spec.js
- fix #264 
- pin coveralls to 3.0.9 since https://github.com/nickmerwin/node-coveralls/issues/280#issuecomment-607443582
> Feature union all

- .babelrc
- .gitignore
- README.md
- build.js
- index.js
- package-lock.json
- package.json
- src/aggregation.js
- src/util.js
> Feature browser

- README.md
- index.js
- package.json
> Bug require

- package.json
- pegjs/postgresql.pegjs
- test/create.spec.js
> support pg uuid type

- package.json
- pegjs/postgresql.pegjs
- src/create.js
- src/util.js
- test/create.spec.js
- support `create trigger`
- support uuid_generate_v4
- support #275 
- [create trigger syntax](https://www.postgresql.org/docs/9.1/sql-createtrigger.html)
> support uuid_generate_v4() and create trigger in postgresql

- package.json
- pegjs/postgresql.pegjs
- src/create.js
- test/create.spec.js
- support `create extension` syntax
- #275
> support pg create extension syntax

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/util.js
- test/select.spec.js
- support jsonb operator  #280 
- support position function query #283
> support jsonb operator, and position function

- DONATIONLIST.md
- README.md
> add new sponsor

- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/constrain.js
- test/create.spec.js
> fix constraint name could not be backticks quoted

- package.json
- pegjs/transactsql.pegjs
- src/column.js
- src/util.js
- test/ast.spec.js
- test/create.spec.js
> support tsql identity

- README.md
- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/create.spec.js
- test/select.spec.js
- support comment only, and before, after or around #292 
- support uniqueidentifier type #296
> support comment only, and UNIQUEIDENTIFIER type

- package.json
- pegjs/transactsql.pegjs
- test/create.spec.js
> support tsql nvarchar and nchar

- pegjs/transactsql.pegjs
- src/util.js
- test/ast.spec.js
- test/create.spec.js
- test/select.spec.js
- support bracket for column and table name #174
> add bracket for column and table name

- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/alter.js
- src/column.js
- src/constrain.js
- src/index-definition.js
- test/cmd.spec.js
- test/create.spec.js
- add DateTime type in Transact-SQL #305 
- add constraint check type in Transact-SQL and MySQL #304
> add datetime type, constraint check for mysql and transactsql

- .eslintrc
- README.md
- package.json
- pegjs/bigquery.pegjs
- src/array-struct.js
- src/column.js
- src/expr.js
- src/limit.js
- src/over.js
- src/parser.js
- src/select.js
- src/sql.js
- src/tables.js
- src/union.js
- src/util.js
- src/window.js
- src/with.js
- test/ast.spec.js
- test/bigquery.spec.js
- support `BigQuery` syntax  #298
> Feature bigquery

- package.json
- pegjs/bigquery.pegjs
- src/select.js
- src/union.js
- test/bigquery.spec.js
- add more test cases
- support select column expression
- support parentheses
- related to #298
> add more test cases

- package.json
- pegjs/transactsql.pegjs
- src/create.js
- src/index-definition.js
- src/util.js
- test/create.spec.js
> support create index in tsql

- package.json
- pegjs/transactsql.pegjs
- test/cmd.spec.js
> fix alter column

- package.json
- pegjs/transactsql.pegjs
- src/command.js
- src/create.js
- src/sql.js
- src/union.js
- test/cmd.spec.js
- support declare in tsql #331
> support declare in tsql

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
- test/update.spec.js
- support `over partition` in hive #341
> fix over_partition bug

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/union.js
- test/ast.spec.js
- support union with order by and limit in last position #344
> support union laster order by and limit clause

- package.json
- pegjs/postgresql.pegjs
- src/expr.js
- src/util.js
- test/select.spec.js
- support `extract` function in pg #354
> support extract function in pg

- package.json
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/select.js
- test/create.spec.js
- test/select.spec.js
- support bool/boolean type in pg #363 
- support time length in pg #364 
- support for update in MySQL #351
> Feature pg bool time mysql forupdate

- package.json
- pegjs/transactsql.pegjs
- test/create.spec.js
- support bracket around data type  #369 
- support `real` type #370 
- support time precision type #371
> support bracket around datatype, real type, time precision in tsql

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
- space is required before `and`, `or` keyword #368
> fix space is required before `and`, `or`

- package.json
- pegjs/mysql.pegjs
- test/select.spec.js
- support boolean type column in where for MySQL #376
> support boolean and not boolean in where

- index.d.ts
Add the column type to Select statement
> Add column type to typescript types

- package.json
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/column.js
- src/create.js
- src/select.js
- src/union.js
- src/util.js
- src/with.js
- test/create.spec.js
- test/index.spec.js
- support create index in pg #383
> support create index in pg

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- typegen.js
- fix prepared statements type bug
> fix new type bug

- package.json
- pegjs/mysql.pegjs
- test/select.spec.js
- support multiple prepared statements #396
> fix multipler prepared statements bug

- package.json
- pegjs/postgresql.pegjs
- src/interval.js
- test/ast.spec.js
- fix interval string bug in pg #404
> support interval string

- README.md
- pegjs/flinksql.pegjs
- src/parser.all.js
- test/select.spec.js
- webpack.config.js
Create a FlinkSQL parser.  The pegjs is developed based on the Postgres.pegjs.  The main motivation is to support: 1) flink specific aggregation function 2) DISTINCT in aggr func.
#Test
```
npm run-script build
npm run-script test
```
> FlinkSQL parser

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/aggregation.js
- test/select.spec.js
- webpack.config.js
- fix #432 
- support 'ilike' #424
> support ARRAY_AGG distinct

- pegjs/bigquery.pegjs
- src/array-struct.js
- test/bigquery.spec.js
> support array()

- pegjs/flinksql.pegjs
- test/select.spec.js
The flinkSQL data type are here:
https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/types.html#data-type-extraction
#Test
npm run-script test
> [FlinkSQL] Add flink specific data types and group window function

- ast/postgresql.ts
- package.json
- pegjs/postgresql.pegjs
- src/util.js
- test/create.spec.js
- test/insert.spec.js
- test/select.spec.js
- test/update.spec.js
> Feature pg

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: fix like and or statement

- pegjs/hive.pegjs
- test/hive.spec.js
> bug: support colume start with number in hive

- index.d.ts
- package.json
- webpack.config.js
> bug: fix export types with correct dir

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: fix where clause with parentheses

- ast/postgresql.ts
- package.json
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/alter.js
- test/cmd.spec.js
> bug: fix add constraint in alter table

- pegjs/mysql.pegjs
- test/cmd.spec.js
- test/create.spec.js
> feat: add bit type in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: support parentheses in where clause

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- fix bug for space before keyword
> bug: space before and or or

- pegjs/hive.pegjs
- test/ast.spec.js
> feat: support cast as string in hive

- pegjs/flinksql.pegjs
- pegjs/postgresql.pegjs
- src/insert.js
- test/insert.spec.js
> feat: support * in returning for pg

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/func.js
- test/ast.spec.js
- test/select.spec.js
> feat: support double colon with as

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/insert.js
- src/update.js
- test/insert.spec.js
> bug: support on duplicate key update set values

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: columnList refresh when get the new table alias

- pegjs/mysql.pegjs
- src/expr.js
- src/show.js
- src/sql.js
- src/union.js
- test/show.spec.js
> Feat show mysql

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/create.js
- test/create.spec.js
- test/postgres.spec.js
- test/select.spec.js
> Feat pg tsql

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/alter.js
- src/array-struct.js
- src/command.js
- src/create.js
- test/cmd.spec.js
- test/create.spec.js
- test/postgres.spec.js
- test/select.spec.js
- fix #458 
- fix #453 
- fix #450 
- fix #449 
- fix #428
> Feat drop index

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/binary.js
- src/util.js
- test/ast.spec.js
- test/insert.spec.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
- test/update.spec.js
> Regexp mysql mariadb

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: fix like before and

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> Refactor pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: remove key in keyword map

- .eslintrc
- pegjs/bigquery.pegjs
- pegjs/mysql.pegjs
- src/util.js
- test/insert.spec.js
> feat: support hex value

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support a multi-line single-quoted string

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: add left as keyword

- package.json
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- check column length with value length in insert stmt
> bug: compare column len with value len in insert stmt

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/command.js
- src/sql.js
- src/union.js
- test/cmd.spec.js
> feat: support desc in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/util.js
- test/bigquery.spec.js
> feat: add case for bigquery, datetime prefix str for all db

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
- fix column list error for extract function
> bug: fix columnList with wrong column

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/create.spec.js
> bug: add fsp for datetime type

- ast/postgresql.ts
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/column.js
- src/expr.js
- test/ast.spec.js
- test/create.spec.js
- typegen.js
> feat: add enum type

- ast/postgresql.ts
- package.json
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/create.spec.js
> refactor: column opt in any order

- ast/postgresql.ts
- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/aggregation.js
- test/select.spec.js
> bug: group_concat in mysql

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: group_concat with expr in all db

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: support order by and limit in bigquery

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> bug: fix offset and ordinal in bigquery

- package.json
- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> Bug from where sqlite

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/sqlite.spec.js
> Bug parentheses where all

- ast/postgresql.ts
- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/alter.js
- src/create.js
- test/cmd.spec.js
- test/create.spec.js
- test/postgres.spec.js
- test/util.spec.js
> Bug alter create in mysql

- pegjs/bigquery.pegjs
- src/column.js
- test/bigquery.spec.js
- fix #739 
- fix #740 
- fix #741
> bug: fix bigquery sql parser bug

- package.json
- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> refactor: remove json keyword in sqlite

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/util.js
- test/create.spec.js
- test/postgres.spec.js
> Create bug mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/ast.spec.js
- test/insert.spec.js
> bug: fix escape char

- .eslintrc
- pegjs/postgresql.pegjs
- src/func.js
- test/postgres.spec.js
> Bug cast array pg

- pegjs/postgresql.pegjs
- src/column.js
- test/postgres.spec.js
> bug: support array index in function args in pg

- pegjs/postgresql.pegjs
- src/select.js
- test/postgres.spec.js
> bug: support distinct on in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: add more scalar fun

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/sql.js
- test/cmd.spec.js
> Feat go mysql tsql

- pegjs/bigquery.pegjs
- src/tables.js
- test/bigquery.spec.js
> bug: support with in from clause in bigquery

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support window function in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support $filedId with parameters

- ast/postgresql.ts
- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/expr.js
- src/over.js
- test/index.spec.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- test/select.spec.js
- test/util.spec.js
> Feat window mysql

- pegjs/postgresql.pegjs
- src/window.js
- test/postgres.spec.js
> bug: fix window function bug with respect nulls

- pegjs/postgresql.pegjs
- src/func.js
- test/postgres.spec.js
> bug: fix cast to expr with binary

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: function argument list with and expr

- ast/postgresql.ts
- package.json
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> Bug on and pg

- pegjs/postgresql.pegjs
- src/tables.js
- test/postgres.spec.js
> Feat tablesample pg

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> support strikethrough in table name for bigquery

- pegjs/hive.pegjs
- pegjs/postgresql.pegjs
- test/bigquery.spec.js
- test/hive.spec.js
> feat: support window function in hive

- pegjs/transactsql.pegjs
- src/exec.js
- src/sql.js
- src/union.js
- src/util.js
- test/select.spec.js
- test/transactsql.spec.js
> feat: support exec procedure in tsql

- package.json
- pegjs/hive.pegjs
- test/hive.spec.js
> feat: support cross join in hive

- README.md
- pegjs/flinksql.pegjs
- test/flink.spec.js
> bug: support current_date in flinksql

- pegjs/hive.pegjs
- test/hive.spec.js
> feat: support == in hive

- pegjs/hive.pegjs
- test/hive.spec.js
> feat: support array access in hive

- package.json
- pegjs/hive.pegjs
- src/column.js
- test/hive.spec.js
> Feat array index hive

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
> bug: support union stmt in in_expr

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/func.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- fix on clause with function and `and expr`
> bug: fix on clause with and function expr, support trim function in pg and mysql

- package.json
- pegjs/hive.pegjs
- src/func.js
- test/hive.spec.js
> feat: support presto sql format in hive

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/expr.js
- src/util.js
- test/select.spec.js
> Bug convert mysql

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> refactor: for window clause in bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: support session user in bigquery

- pegjs/bigquery.pegjs
- src/binary.js
- src/tables.js
- test/bigquery.spec.js
> Feat pivot bigquery

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/select.js
- src/tables.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
- fix #914 
- support `select ... into` in MySQL
- support `from values` in MySQL
> support `select ... into` and `from values` in MySQL 

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/aggregation.js
- test/bigquery.spec.js
> bug: distinct to sql with parentheses

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/bigquery.spec.js
- test/mysql-mariadb.spec.js
> bug: fix select column with star

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> bug: create table as in sqlite

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> bug: as is optional when from values list in pg

- pegjs/postgresql.pegjs
- src/expr.js
- test/postgres.spec.js
> feat: support dollar-quoted string in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> bug: fix unit is not column for timestampdiff and timestampadd in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/column.js
- src/tables.js
- test/mysql-mariadb.spec.js
> support create table column with on update current_timestamp in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> bug: support ignore in insert in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/select.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> Feat select into pg mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support select; in pg

- pegjs/postgresql.pegjs
- src/expr.js
- test/postgres.spec.js
> feat: support insert in with clause in pg

- ast/postgresql.ts
- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/create.js
- test/create.spec.js
- webpack.config.js
> feat: support create view in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/ast.spec.js
> bug: fix cast ast sqlify without parentheses bug

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/util.js
- test/mysql-mariadb.spec.js
> feat: support backticks in the in_op_right in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> refactor: support triple single quote in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> bug: fix rlike column

- pegjs/postgresql.pegjs
- src/limit.js
- test/postgres.spec.js
> bug: limit is optional in limit offset clause in pg

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> bug: support empty space after :: in pg

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/column.js
- src/index-definition.js
- src/util.js
- src/with.js
- test/ast.spec.js
- test/cmd.spec.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
- test/util.spec.js
> Feat col literal mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support placeholder in limit clause

- pegjs/bigquery.pegjs
1.  Added optional FROM clause in update statement
2.  Made FROM clause optional in delete statement
3. Made INTO clause optional in [Insert statement](https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#insert_statement)
4. Added optional [Table Hint](https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#statement_hints) - Partial support
5. Added optional [Table Sample](https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#tablesample_operator)
6. Added optional COLLATE in [order clause](https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#order_by_clause)
7. Added empty array support
> Handled optional keyword in multiple queries

- package-lock.json
- pegjs/bigquery.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/transactsql.pegjs
- src/util.js
- test/mysql-mariadb.spec.js
- test/transactsql.spec.js
- webpack.config.js
- fix #1058 
- fix #1057 
- fix #1056 
- fix #1055 
- fix #1043
> feat: support over clause after aggregation function

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/transactsql.pegjs
- src/command.js
- test/mysql-mariadb.spec.js
- test/transactsql.spec.js
> feat: support drop table if exists in mysql and tsql

- ast/postgresql.ts
- index.d.ts
- package.json
- webpack.config.js
> refactor: update prepublish issue

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: assigning a value to a SQL variable within a SELECT query in mysql

- .eslintrc
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- src/util.js
- test/insert.spec.js
- test/mysql-mariadb.spec.js
> fix: support hexadecimal literals in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/alter.js
- test/cmd.spec.js
- test/mysql-mariadb.spec.js
> feat: support alter table auto_increment in mariadb

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/show.js
- test/mysql-mariadb.spec.js
> feat: support show create view in mysql

- package.json
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- src/column.js
- test/postgres.spec.js
> refactor: support nested json traversal

- pegjs/postgresql.pegjs
- src/expr.js
- test/postgres.spec.js
> feat: support nulls after order by clause in pg

- pegjs/postgresql.pegjs
- src/tables.js
- test/postgres.spec.js
> feat: support lateral in pg

- pegjs/postgresql.pegjs
- src/binary.js
- test/postgres.spec.js
> feat: support escape after like op in pg

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> bug: fix insert ignore without columns in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
Closes https://github.com/taozhi8833998/node-sql-parser/issues/1097
> MySQL: add parentheses support after FROM clause

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/tables.js
- test/mysql-mariadb.spec.js
- fix #1097 
- related to #1098
> refactor: add parentheses support after FROM clause

- pegjs/bigquery.pegjs
- pegjs/flinksql.pegjs
- pegjs/postgresql.pegjs
- test/bigquery.spec.js
> fix: add date field in extract function in bigquery

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> Feat blob mysql

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> fix: left as keyword support left join in tsql

- pegjs/postgresql.pegjs
- src/func.js
- test/postgres.spec.js
> feat: add timezone for time and timestamp datatype in pg

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/column.js
- src/expr.js
- test/mysql-mariadb.spec.js
> Feat fulltext search mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- src/util.js
- test/mysql-mariadb.spec.js
> feat: support bit operator in mysql

- pegjs/transactsql.pegjs
- test/ast.spec.js
- test/create.spec.js
- test/transactsql.spec.js
> bug: fix bracket schema when fully qualified table name in tsql

- pegjs/transactsql.pegjs
- src/tables.js
- test/ast.spec.js
- test/create.spec.js
- test/transactsql.spec.js
> Feat: support table hint in transactsql

- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- test/postgres.spec.js
- test/transactsql.spec.js
Added support for nested block comments to PostgreSQL and Transact-SQL.
Fixes #1130
> Support nested block comments

- index.d.ts
- package.json
> fix: get the correct type

- ast/postgresql.ts
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/create.spec.js
> fix: space or comments could be placed between "if not exists" in all db

- index.js
> fix: global is not defined in browser

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> fix: positive sign before number in all db

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
- refactor #1160, xor is only supported in mysql and mariadb
- fix #1154 
- fix #1149
> fix: space are required, and xor is only supported in mysql and mariadb

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support bytea data type in pg

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> refactor: support schema in bigquery

- test/bigquery.spec.js
> refactor: add or operator test case in bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> Refactor right func name bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: extract filed in bigquery

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- test/bigquery.spec.js
- test/update.spec.js
> refactor: support keyword as function name

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: insert set in mysql and mariadb

- pegjs/postgresql.pegjs
- src/aggregation.js
- test/postgres.spec.js
> feat: support filter after aggregate function in pg

- ast/postgresql.ts
- package.json
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: decimal without prefix zero in pg

- pegjs/bigquery.pegjs
1. Multi statement
2. Array subscript
3. Nested struct
> Bigquery fixes

- pegjs/bigquery.pegjs
- pegjs/mysql.pegjs
- src/union.js
- test/bigquery.spec.js
> Fix multiple over bigquery

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/bigquery.spec.js
> fix: current_date without parentheses in all db

- pegjs/bigquery.pegjs
- src/select.js
- test/bigquery.spec.js
> feat: support qualify in bigquery

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: values could be table name in pg

- package.json
> fix: types definition

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/sqlite.spec.js
> fix: escape single quote in sqlite

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> refactor: remove session keyword

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support $ in alias ident in mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: when double_quoted in column while not in columnList in pg

- pegjs/mysql.pegjs
- test/create.spec.js
Fixes a wrong implementation from #1239
> Fix generated columns with additional column definitions

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/aggregation.js
- test/mysql-mariadb.spec.js
> fix: case insensitive for separator

- pegjs/bigquery.pegjs
- src/util.js
- test/bigquery.spec.js
> feat: support @ as parameter prefix in bigquery

- .gitignore
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support bigserial and real data type in pg

- .gitignore
- ast/postgresql.ts
- package.json
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- related to bug3 in #1236 
- fix #1220
> Refactor table name pg

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [set operations](https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/table/sql/queries/set-ops/) in Flink.
Please review carefully, as this "language" is very new to me :-)
> feat: support set operations in flink

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/util.js
- test/mysql-mariadb.spec.js
- related to #1148, support natural charset strings
> feat: support natural charset strings in mysql

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- src/expr.js
- src/func.js
- src/show.js
- test/postgres.spec.js
> fix: cast quoted data type in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support geometry type in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> Fix having clause with parentheses

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/flink.spec.js
> refactor: concatenation operator precedence

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/aggregation.js
- test/bigquery.spec.js
> Fix count args

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: add integer type in bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: support ISOWEEK in bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> Fix column list bigquery

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> fix: support autoincreasment, boolean type and data type could be optional in create table syntax for sqlite

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- test/mysql-mariadb.spec.js
> fix: regexp right could be function call in mysql

- pegjs/mysql.pegjs
> fix: add week interval unit

- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/update.spec.js
> fix: tableList is not correct in update clause

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/delete.spec.js
- test/update.spec.js
> fix: delete and update tableList and columnList

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/func.js
- test/bigquery.spec.js
> fix: support safe_cast in bigquery

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/select.spec.js
- fix #1305 
- related to #1310
> fix: limit offset clause support var statement in pg

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/union.js
- test/ast.spec.js
- test/mysql-mariadb.spec.js
> Feat set op

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/index-definition.js
- test/mysql-mariadb.spec.js
> feat: create table index with length in mysql

- pegjs/bigquery.pegjs
- pegjs/flinksql.pegjs
- pegjs/postgresql.pegjs
- test/bigquery.spec.js
> fix: extract from column

- pegjs/postgresql.pegjs
- src/func.js
- test/postgres.spec.js
> feat: column now at time zone in pg

- pegjs/transactsql.pegjs
- src/util.js
- test/transactsql.spec.js
> feat: support top with parentheses in tsql

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> fix: with clause column ref list

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/delete.js
- src/update.js
- test/mysql-mariadb.spec.js
> feat: support update clause after with in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> feat: support cross join in mysql

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- src/column.js
- src/util.js
- test/postgres.spec.js
> feat: support returning stmt in pg

- pegjs/bigquery.pegjs
- src/expr.js
- test/bigquery.spec.js
- test/postgres.spec.js
> feat: support unnest after in expr in bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: support logical operator in where clause in bigquery

- pegjs/bigquery.pegjs
- src/expr.js
- src/func.js
- test/bigquery.spec.js
> Feat any value bigquery

- pegjs/bigquery.pegjs
- src/column.js
- test/bigquery.spec.js
> bug: access record type in bigquery

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/command.js
- test/mysql-mariadb.spec.js
> feat: support drop database and schema in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support mediumint, set and year type in create table for mysql

- pegjs/mariadb.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
- test/transactsql.spec.js
> Fix type keyword mssql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> feat: support with table name in sqlite

- pegjs/postgresql.pegjs
- src/update.js
- test/postgres.spec.js
> feat: support update clause with from item in pg

- pegjs/postgresql.pegjs
- src/command.js
- test/postgres.spec.js
> fix: drop index in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support with before update stmt

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> Fix concate pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/show.js
- test/mysql-mariadb.spec.js
> feat: show create table in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
> refactor: support extract time in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> fix: support on reference in alter table in pg

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> refactor: support isoyear as interval arg in bigquery

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> feat: add blob type in sqlite

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/command.js
- test/mysql-mariadb.spec.js
> feat: support drop view stmt in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: alter add column in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: convert fun with number args in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/show.js
- test/mysql-mariadb.spec.js
> feat: support show statement in mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
Here is my attempt at a fix for issue 1403.
> Parse and test OID types

- pegjs/flinksql.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/index-definition.js
- test/create.spec.js
- test/transactsql.spec.js
> feat: refactor all column order

- ast/postgresql.ts
- index.js
- package.json
- pegjs/postgresql.pegjs
- webpack.config.js
> feat: works in web-woker

- ast/postgresql.ts
- index.js
- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/mysql-mariadb.spec.js
- webpack.config.js
> Feat alter table modify column mysql

- pegjs/bigquery.pegjs
- src/sql.js
- src/union.js
- test/bigquery.spec.js
- types.d.ts
> refactor: change bigquery type definition

- README.md
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> fix: select from select_stmt in all db

- pegjs/transactsql.pegjs
- src/binary.js
- src/tables.js
- test/transactsql.spec.js
> feat: support pviot and unpviot in tsql

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> feat: support with clause before update stmt in tsql

- pegjs/postgresql.pegjs
- src/expr.js
- src/tables.js
- test/postgres.spec.js
> Fix temp table contructor pg

- pegjs/transactsql.pegjs
- src/alter.js
- test/transactsql.spec.js
> feat: support alter view in tsql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: add schema prefix in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support ntile function and character data type in pg

- pegjs/postgresql.pegjs
- src/func.js
- test/postgres.spec.js
> fix: cast with ->> in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
- fix #1460 
- related to #1461
> feat: support escape after like op in mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support !~ operator

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- test/mysql-mariadb.spec.js
- test/sqlite.spec.js
> fix: optional number after dot in mysql and sqlite

- LICENSE
- README.md
- ast/postgresql.ts
- package.json
- pegjs/postgresql.pegjs
- src/insert.js
- test/postgres.spec.js
> feat: support on conflict for insert stmt in pg

- .eslintrc
- pegjs/flinksql.pegjs
- src/tables.js
- test/flink.spec.js
> Feat table tumble flink

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/alter.js
- src/column.js
- src/create.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- test/transactsql.spec.js
- #1471 
- fix #1500 
- fix #1501 
- fix #1502 
- support `alter schema` in pg
> feat: support alter schema in pg, and fix convert fun args, on update current_timestamp args in mysql

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
> feat: support create view, fix build error in pg

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> fix: set dataType in mysql

- test/transactsql.spec.js
> refactor: add test case for tsql

- ast/postgresql.ts
- package.json
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/bigquery.spec.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> refactor: fix slow parser in pg

- ast/postgresql.ts
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/expr.js
- src/union.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
> fix: parse nested sub queries

- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/tables.js
- test/transactsql.spec.js
> feat: support from values, server.db.schema.table in tsql

- pegjs/transactsql.pegjs
- src/select.js
- test/transactsql.spec.js
> feat: support for xml and fix cast to datatime2 in tsql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/command.js
- src/sql.js
- src/union.js
- src/util.js
- test/mysql-mariadb.spec.js
> Feat grant mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- src/create.js
- test/sqlite.spec.js
- test/transactsql.spec.js
> feat: support create trigger in sqlite

- pegjs/flinksql.pegjs
- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
- support create trigger for #1471 
- add test cases for #402
> Refactor create trigger pg

- pegjs/hive.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- test/cmd.spec.js
- test/postgres.spec.js
- test/transactsql.spec.js
> fix: ident_name in all db

- README.md
- pegjs/snowflake.pegjs
- src/expr.js
- src/func.js
- src/parser.all.js
- src/util.js
- test/snowflake.spec.js
> feat: support snowflake

- README.md
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/command.js
- test/postgres.spec.js
> feat: support grant stmt in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- src/command.js
- src/sql.js
- src/union.js
- test/ast.spec.js
- test/postgres.spec.js
- support revoke statement in pg for #1471
> feat: support revoke in pg

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/expr.js
- test/postgres.spec.js
- test/select.spec.js
> refactor: remove order by default asc sort type in ast

- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/alter.js
- src/command.js
- src/create.js
- src/proc.js
- src/sql.js
- src/union.js
- test/postgres.spec.js
- test/select.spec.js
- support create function for #1471
> Feat create function pg

- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
- support `create aggregate` for #1471
> Feat create aggregate pg

- pegjs/postgresql.pegjs
- support record type for #1471
> feat: support record data type and raise stmt in pg

- pegjs/postgresql.pegjs
- src/command.js
- src/sql.js
- src/union.js
- test/postgres.spec.js
- support raise stmt in pg for #1471
> Feat raise stmt pg

- ast/postgresql.ts
- package.json
- pegjs/postgresql.pegjs
> refactor: update pg definition

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/over.js
- test/mysql-mariadb.spec.js
> fix: on update now() in mysql

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/ast.spec.js
- test/cmd.spec.js
- test/create.spec.js
- test/flink.spec.js
- test/insert.spec.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
- test/sqlite.spec.js
- test/update.spec.js
> fix: keep origin quote string type

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: support order by for column in create constaint in mysql

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> fix: support keyword as column name in create table sql in sqlite

- src/column.js
- src/util.js
- test/sqlite.spec.js
> fix: sqlify to mariadb for autoincrement from sqlite

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- test/create.spec.js
- test/sqlite.spec.js
> fix: primary key missing when have unique in sqlify

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: character varying as data type in pg

- pegjs/mariadb.pegjs
- src/column.js
- src/constrain.js
- src/util.js
- test/sqlite.spec.js
> fix: sqlify from mariadb ast to sqlite

- package.json
> refactor: upgrade version

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/postgres.spec.js
> fix: datatype length missing parentheses in all db

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: join multiple tables in mysql

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> refactor: support real in sqlite

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/util.js
- test/mysql-mariadb.spec.js
> fix: convert fun in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support checksum and delay_key_write table option in create table

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
> Feat db prefix column mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: add more extract field in mysql

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: extract filed bug in bigquery

- pegjs/bigquery.pegjs
- src/util.js
- test/bigquery.spec.js
- test/snowflake.spec.js
> Fix sqlify column snowflake

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: create table failed in bigquery

- types.d.ts
> fix: column type definition

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/cmd.spec.js
- test/mysql-mariadb.spec.js
> fix: table name starts with number or lodash in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support show create event, trigger and procedure in mysql

- ast/postgresql.ts
- pegjs/mysql.pegjs
`INSERT IGNORE INTO table SET id=1` should parse in mysql
> support ignore in insert set

- pegjs/mariadb.pegjs
- test/mysql-mariadb.spec.js
- insert ignore into
- add test case for #1642
> feat: support insert ignore into in mysql

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> fix: inner join in mssql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- test/mysql-mariadb.spec.js
> fix: set column name can be reserved word

- ast/postgresql.ts
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
Reverts taozhi8833998/node-sql-parser#1664
> Revert "fix unary operation"

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/expr.js
- test/ast.spec.js
- test/mysql-mariadb.spec.js
> feat: add unary operator in binary expr in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support like param in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/mysql-mariadb.spec.js
> refactor: format unary

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- types.d.ts
> refactor: update type for where field

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
- support drop index or key in mysql
> feat: support drop index and key in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: aggreate should throw error when args is not right in mysql

- package.json
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: add double precision type in pg

- types.d.ts
> refactor: add function type

- pegjs/postgresql.pegjs
- src/expr.js
- src/func.js
- test/postgres.spec.js
> feat: support crosstab tablefunc in pg

- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- src/create.js
- test/sqlite.spec.js
> feat: support create view stmt in sqlite

- pegjs/mysql.pegjs
Add ENGINE_ATTRIBUTE, SECONDARY_ENGINE_ATTRIBUTE and (DATA|INDEX) DIRECTORY to CREATE TABLE.
> engine attributes and data directories

- pegjs/bigquery.pegjs
- src/array-struct.js
- test/bigquery.spec.js
> fix: array sqlify not right in bigquery

- package.json
- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: column offset in bigquery

- pegjs/bigquery.pegjs
- src/column.js
- test/bigquery.spec.js
> fix: table prefix star with except in bigquery

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: crosstab in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: alter table drop index with identified in mysql

- types.d.ts
Fixes https://github.com/taozhi8833998/node-sql-parser/issues/1701
> Fix some AST typescript types

- pegjs/bigquery.pegjs
- src/column.js
- src/expr.js
- src/json.js
- test/bigquery.spec.js
> feat: support json type, fix array column vistior in bigquery

- package.json
- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: json array access in where clause in bigquery

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: alter table modify column keyword is optional in mysql

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/case.js
- test/bigquery.spec.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
> fix: count function args with or expr in all db

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support accentuated characters in column of pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: case when then expr with additive in pg

- ast/postgresql.ts
- pegjs/postgresql.pegjs
> refactor: update type definition

- pegjs/flinksql.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/aggregation.js
- src/command.js
- src/create.js
- src/func.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> feat: support create user in mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: as double quoted in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support intersect and except op in pg

- README.md
- ast/postgresql.ts
- pegjs/noql.pegjs
- src/parser.all.js
- src/parser.js
- src/util.js
- test/noql.spec.js
> feat: add noql dialect

- pegjs/mariadb.pegjs
- test/mysql-mariadb.spec.js
> fix: data index in mariadb

- pegjs/mariadb.pegjs
- pegjs/snowflake.pegjs
- test/mysql-mariadb.spec.js
- test/snowflake.spec.js
> Feat double slash comment snowflake

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> feat: support number data type in snowflake

- pegjs/postgresql.pegjs
- src/sql.js
- test/postgres.spec.js
> feat: support set to value in pg

- package.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: check constraint support and expr in mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: double quoted column cast in pg

- pegjs/postgresql.pegjs
- src/sql.js
- src/transaction.js
- src/union.js
- test/postgres.spec.js
> feat: support transaction keyword in pg

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: for publish

- package-lock.json
- package.json
> refactor: downgrade chai

- .github/workflows/npm-publish-github-packages.yml
> fix: github action

- pegjs/bigquery.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- test/noql.spec.js
> fix: intersect multiple sql in nosql

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: add interval week unit in bigquery

- pegjs/postgresql.pegjs
- src/column.js
- src/insert.js
- src/update.js
- test/ast.spec.js
- test/cmd.spec.js
- test/create.spec.js
- test/index.spec.js
- test/insert.spec.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- test/select.spec.js
- test/transactsql.spec.js
- test/update.spec.js
> Refactor quoted type

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/show.js
- test/mysql-mariadb.spec.js
> fix: show index from table in mysql

- pegjs/postgresql.pegjs
- src/func.js
- test/postgres.spec.js
> refactor: support quoted function name, quoted schema name in pg

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> feat: support cross and outer apply in tsql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: column ref in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support custom data type by create type in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: table name starts with number or lodash ignore keywords in mysql

- pegjs/postgresql.pegjs
- src/command.js
- src/tables.js
- test/postgres.spec.js
- test/redshift.spec.js
- test/transactsql.spec.js
> fix: truncate table with option in pg

- pegjs/hive.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- src/column.js
- src/update.js
- test/postgres.spec.js
> feat: support updating JSON using subscripting in pg

- README.md
- pegjs/athena.pegjs
- pegjs/transactsql.pegjs
- src/func.js
- src/parser.all.js
- test/athena.spec.js
- test/transactsql.spec.js
> feat: support athena

- types.d.ts
complements https://github.com/taozhi8833998/node-sql-parser/pull/1827
> refactor: new function name types

- .github/workflows/npm-publish-github-packages.yml
- ast/postgresql.ts
- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> Refactor type

- ast/postgresql.ts
- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/mysql-mariadb.spec.js
- test/trino.spec.js
> fix: slow deep nest function sql in all db

- pegjs/snowflake.pegjs
- src/column.js
- test/snowflake.spec.js
> feat: support traversing semi-structured data with colons(:) in snowflake

- pegjs/snowflake.pegjs
- src/expr.js
- src/json.js
- test/snowflake.spec.js
> feat: support json visitor in snowflake

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/binary.js
- test/mysql-mariadb.spec.js
> fix: count args in mysql

- package-lock.json
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/alter.js
- src/binary.js
- test/mysql-mariadb.spec.js
> Fix alter table after mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: json as table function in pg

- pegjs/transactsql.pegjs
- src/tables.js
- test/transactsql.spec.js
> feat: support temporal table in tsql

- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
> feat: support declaritive partitions in pg

- pegjs/transactsql.pegjs
- src/assign.js
- test/transactsql.spec.js
> feat: support more set stmt in tsql

- pegjs/flinksql.pegjs
- src/expr.js
- test/flink.spec.js
> feat: support map expr in flink

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: check constraint in mysql

- pegjs/flinksql.pegjs
- src/expr.js
- src/func.js
- test/flink.spec.js
> feat: support json object in flinksql

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/redshift.spec.js
> fix: unary operator in redshift

- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/trino.pegjs
- src/aggregation.js
- test/postgres.spec.js
> fix: string_agg function in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: sum expr in mysql

- test/mysql-mariadb.spec.js
> refactor: add escape test case for mysql

- package.json
- pegjs/athena.pegjs
- pegjs/db2.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/athena.spec.js
> fix: over partition and extract in athena

- pegjs/redshift.pegjs
- add getLocationObject function
> fix: add getLocationObject function in redshift

- package-lock.json
- package.json
Reverts taozhi8833998/node-sql-parser#1898
> Revert "build(deps-dev): bump chai from 4.4.1 to 5.1.1"

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
Hello,
We have been using node-sql-parser as part of our project. Thanks for this package!
This PR is an attempt to fix this issue: https://github.com/taozhi8833998/node-sql-parser/issues/1912
Please leave comments if needed.
Thanks!
> Added support for additional snowflake data types

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/create.js
- test/create.spec.js
> fix: create database with quoted db name in all dialect

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- src/column.js
- src/func.js
- test/mysql-mariadb.spec.js
- test/sqlite.spec.js
> feat: support create table in mysql 8.x and drop view in sqlite

- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- test/postgres.spec.js
> fix: support if exists in drop table stmt in pg

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/column.js
- src/func.js
- test/trino.spec.js
- types.d.ts
> fix: between star column, support bracket in function args

- types.d.ts
> refactor: update function name and args type

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> fix: reference table bug in sqlite

- ast/postgresql.ts
- pegjs/bigquery.pegjs
- pegjs/postgresql.pegjs
- src/create.js
- change to `replace` filed
- fix #1946
> refactor: change or_replace to replace field and fix npm run build error

- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> feat: support check constraints in sqlite

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> feat: support alter table rename column in sqlite

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> fix: column should not include keywords in sqlite

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: ilike operator in pg

- ast/postgresql.ts
- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/select.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
- types.d.ts
> feat: support with rollup in mysql

- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- test/postgres.spec.js
> feat: support check constraints in pg

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/create.js
- test/snowflake.spec.js
> Feat snowflake

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/snowflake.spec.js
> feat: support top clause and fix multiple union all in snowflake

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> feat: support select into and temporary table in tsql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/explain.js
- src/sql.js
- src/union.js
- test/mysql-mariadb.spec.js
> feat: support explain stmt in mysql

- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/trino.pegjs
- src/column.js
- src/func.js
- test/postgres.spec.js
> feat: support data type array in pg

- src/expr.js
- test/postgres.spec.js
> fix: binary expr as fun args in pg

- pegjs/snowflake.pegjs
- src/column.js
- src/tables.js
- test/snowflake.spec.js
> feat: support generator table rows in snowflake

- pegjs/snowflake.pegjs
- pegjs/transactsql.pegjs
- test/snowflake.spec.js
> feat: support unpivot funtion in snowflake

- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
> refactor: support create type range and columns in pg

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> refactor: default expr in all dialects

- pegjs/snowflake.pegjs
- src/column.js
- test/snowflake.spec.js
> feat: support * exclude columns in snowflake

- pegjs/sqlite.pegjs
- src/util.js
- test/sqlite.spec.js
> refactor: change sqlite identify from bracket to double quotation /  support double equal symbol and subquery

- src/column.js
- test/create.spec.js
- test/mysql-mariadb.spec.js
> fix: column options order in mysql

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/trino.pegjs
- src/func.js
- test/ast.spec.js
> fix: jsonb operator ast order in pg

- pegjs/postgresql.pegjs
- src/column.js
- test/postgres.spec.js
> fix: column constraing in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: quoted column data type in pg

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/trino.pegjs
- src/aggregation.js
- src/column.js
- src/func.js
- test/ast.spec.js
- test/mysql-mariadb.spec.js
> refactor: change jsonb to binary_expr in all dialects

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> refactor: support reserved words in as clause in snowflake

- pegjs/bigquery.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- test/postgres.spec.js
- test/redshift.spec.js
> refactor: support no space before line comment

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> fix: mixed cast and jsonb expr

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: add timestamptz data type in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: handle literal string to function name in mysql

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> fix: key reserved word in sqlite

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/trino.pegjs
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> fix: jsonb bug in pg

- pegjs/athena.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/snowflake.spec.js
> fix: in op right could be expr

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/tables.js
- test/mysql-mariadb.spec.js
> fix: from table with alias in parentheses

- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: create scheme error in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: constraint with quoted name

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/trino.spec.js
> fix: add location when throw args error

- pegjs/mysql.pegjs
- pegjs/trino.pegjs
> refactor: fix location different for same sql in different dialect

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> fix: limit is not reserved keyword in snowflake

- pegjs/athena.pegjs
- src/func.js
- test/athena.spec.js
> fix: array type could be warpped by angle brackets in athena

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> fix: limit as keyword in snowflake

- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- src/expr.js
- src/transaction.js
- test/postgres.spec.js
> feat: support start transaction in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/mysql-mariadb.spec.js
> fix: text data type can have length setting in mysql

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> fix: over partition clause after func call in snowflake

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: convert function to signed in mysql

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/transactsql.spec.js
> fix: convert function and as chinese chars in transactsql

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> refactor: add loc property to func_call in all dialects

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: reserved keyword as column name in postgresql

- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- test/redshift.spec.js
> feat: support position function in redshift

- pegjs/flinksql.pegjs
- src/create.js
- test/flink.spec.js
> feat: support with clause in create table stmt for flink

- types.d.ts
> fix: add _next field to Select interface

- pegjs/postgresql.pegjs
- src/expr.js
- src/select.js
- test/postgres.spec.js
> fix: distinct on jsonb expr in pg

- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
> refactor: support return stmt sql body in create function in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
Code has not yet been verified.
Discussion https://github.com/taozhi8833998/node-sql-parser/discussions/2145 - don't know how to build NSP
Issue #2146
> Support 'mod' operator for mysql/mariadb

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support mod operator in mysql

- README.md
- pegjs/flinksql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/snowflake.spec.js
> refactor: add schema and server name in tableList

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support bit data type in mysql

- pegjs/mysql.pegjs
- types.d.ts
> refactor: Insert_Replace values chould be Select type

- pegjs/bigquery.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- test/noql.spec.js
> fix: except op in noql

- test/sqlite.spec.js
> refactor: add more test cases for sqlite

- pegjs/sqlite.pegjs
- src/create.js
- src/tables.js
- test/sqlite.spec.js
> feat: support create table option in sqlite

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/create.js
- test/sqlite.spec.js
> feat: support create index in sqlite

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: column name can start with digit in mysql

- types.d.ts
> refactor: add type alias for backward-compatible

- types.d.ts
> refactor: add more type definition

- src/column.js
- src/parser.js
- test/ast.spec.js
> feat: export columns method

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/create.js
- test/create.spec.js
> refactor: change definer expr in mysql

- pegjs/postgresql.pegjs
- src/func.js
- test/ast.spec.js
- test/postgres.spec.js
- support substring function in postgresql
> feat: support substring in pg

- pegjs/postgresql.pegjs
- src/column.js
- src/expr.js
- test/postgres.spec.js
- types.d.ts
> feat: support at time zone in pg

- src/column.js
- test/create.spec.js
- test/mysql-mariadb.spec.js
> fix: not null position after generated column in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/tables.js
- test/mysql-mariadb.spec.js
- types.d.ts
> fix: from clause with multiple parentheses in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support lateral derived tables in mysql

- pegjs/postgresql.pegjs
- src/assign.js
- test/postgres.spec.js
> feat: support set time zone in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: support if not exists stmt in create index stmt in pg

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> refactor: support listagg function in snowflake

- pegjs/athena.pegjs
- test/athena.spec.js
> refactor: as can be ignore when UNNEST in athena

- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
> feat: support include columns in create index for pg

- pegjs/mysql.pegjs
- pegjs/sqlite.pegjs
- src/alter.js
> refactor: alter table first with optional column in mysql

- package-lock.json
Fixes this issue https://github.com/taozhi8833998/node-sql-parser/issues/2237
> Fix vulnerabilities via npm audit fix

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> feat: support float4 and float8 in snowflake

- pegjs/athena.pegjs
- pegjs/transactsql.pegjs
- test/athena.spec.js
- test/transactsql.spec.js
> fix: double quoted table mentions in athena and tsql

- pegjs/athena.pegjs
> fix: support real type in athena

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support subquery in limit clause

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/interval.js
- src/window.js
- test/snowflake.spec.js
> feat: support range expr as window frame in snowflake

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> fix: over window frame current row in snwoflake

- pegjs/athena.pegjs
- test/athena.spec.js
> fix: over partition clause in athena

- pegjs/athena.pegjs
- pegjs/mysql.pegjs
- test/athena.spec.js
> fix: quoted function name, from multiple parentheses table in athena

- pegjs/athena.pegjs
- src/tables.js
- test/athena.spec.js
> feat: support parentheses value in athena

- pegjs/athena.pegjs
- src/util.js
- test/athena.spec.js
> feat: support u& string in athena

- pegjs/athena.pegjs
- test/athena.spec.js
> feat: support parse -> operator in athena

- pegjs/athena.pegjs
- test/athena.spec.js
> fix: array_agg func in athena

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/column.js
- test/ast.spec.js
- test/bigquery.spec.js
- test/create.spec.js
- test/delete.spec.js
- test/mysql-mariadb.spec.js
- test/select.spec.js
- test/update.spec.js
> fix: collate in mysql

- pegjs/athena.pegjs
- pegjs/flinksql.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/trino.pegjs
- test/mysql-mariadb.spec.js
> feat: support trim expr in all db

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/func.js
- test/redshift.spec.js
> feat: support multiple cast in all db

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: wrapped column_ref in bigquery

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: math operation together with array access in bigquery

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support drop view in pg

- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/trino.pegjs
- src/window.js
- test/postgres.spec.js
- test/redshift.spec.js
- test/snowflake.spec.js
> refactor: windows function ignore nulls in all db

- pegjs/db2.pegjs
- test/db2.spec.js
> fix: fetch as keyword in db2

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> feat: support string_agg function in tsql

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> feat: support for json path in tsql

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> fix: as quoted ident in tsql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: assign stmt with alias in mysql

- pegjs/transactsql.pegjs
- test/transactsql.spec.js
> fix: varchar and varbinary max in tsql

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: support table function in bigquery

- types.d.ts
> fix: add collate type in column_ref

- src/parser.js
- test/select.spec.js
> fix: whiteList should be exact match

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> fix: support rows between following and following window func in all db

- pegjs/postgresql.pegjs
- src/expr.js
- src/func.js
- test/postgres.spec.js
> feat: support make_interval func in pg

- pegjs/postgresql.pegjs
- src/column.js
- test/postgres.spec.js
> refactor: support more geometry type in pg

- pegjs/transactsql.pegjs
- src/column.js
- test/transactsql.spec.js
> feat: support table-valued function in tsql

- pegjs/flinksql.pegjs
- pegjs/mariadb.pegjs
- src/delete.js
- src/insert.js
- src/util.js
- test/mariadb/mariadb.spec.js
> feat: support insert returning in mariadb

- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/transactsql.spec.js
> feat: support update set from table in tsql

- pegjs/transactsql.pegjs
- src/constrain.js
- test/transactsql.spec.js
> feat: support add constraint default expr in tsql

- pegjs/mariadb.pegjs
- test/mariadb/mariadb.spec.js
> feat: support uuid type in mariadb

- pegjs/transactsql.pegjs
- src/func.js
- test/transactsql.spec.js
> feat: support within group function in tsql

- pegjs/db2.pegjs
- src/select.js
- test/db2.spec.js
> feat: support except in db2

- pegjs/postgresql.pegjs
- src/collate.js
- test/postgres.spec.js
> refactor: support collate schema in pg

- src/column.js
- src/constrain.js
> refactor: database ignore upper or lower case for sqlite

- pegjs/bigquery.pegjs
- src/column.js
- src/func.js
- test/bigquery.spec.js
> fix: column offset in cast expr in bigquery

- pegjs/postgresql.pegjs
- src/command.js
- test/postgres.spec.js
> feat: support drop type in pg

- pegjs/postgresql.pegjs
- src/create.js
- test/postgres.spec.js
> feat: support unlogged table in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> Fix newline string mariadb

- types.d.ts
> refactor: add scale property to DataType

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mariadb/mariadb.spec.js
> fix: default row format in mariadb

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/alter.js
- test/mysql-mariadb.spec.js
> feat: support alter partition in mysql

- pegjs/db2.pegjs
- pegjs/transactsql.pegjs
- src/limit.js
- test/db2.spec.js
> fix: support row keyword in db2 and tsql

- types.d.ts
> fix: cast type definition

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> refactor: support function calls in column defaults for pg

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
> fix: additive expr in column for snowflake

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: alter table owner to in pg

- pegjs/db2.pegjs
- src/limit.js
- test/db2.spec.js
> fix: fetch offset in db2

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> feat: support transaction stmt in mysql

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
Addresses https://github.com/taozhi8833998/node-sql-parser/issues/2433
> fix(snowflake): support try_cast

- types.d.ts
> feat: add returning stmt to type definition

- pegjs/sqlite.pegjs
- src/insert.js
- test/sqlite.spec.js
> fix: support insert or action in sqlite

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
Fixes https://github.com/taozhi8833998/node-sql-parser/issues/2464
> fix: snowflake double quote escape

- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> fix: contant string with case sensitive in all db

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> fix: update set item support full expr in all db

- pegjs/bigquery.pegjs
- src/insert.js
- src/tables.js
- src/util.js
- test/bigquery.spec.js
> Fix table name

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: keyword as database and table name in mysql

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support text array type in pg

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> fix: quoted column name in sqlite

- src/over.js
- test/sqlite.spec.js
> fix: over partition sqlify failed

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/tables.js
- test/mysql-mariadb.spec.js
- test/update.spec.js
> fix: multiple joins in mysql and mariadb

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: xor operator in mysql and mariadb

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support network address type in pg

- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/trino.pegjs
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> refactor: column name starts with an accent

- types.d.ts
> fix: collate could be null in type definition

- src/column.js
- test/snowflake.spec.js
> fix: multiple array index when sqlify back

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
> feat: support group_concat in sqlite

- pegjs/postgresql.pegjs
- src/column.js
- src/util.js
- test/postgres.spec.js
> fix: custom type support schema prefix in pg

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: add bit data type in pg
