- .babelrc
- .travis.yml
- build.js
- package.json
- yarn.lock
It does not appear that a minimum engine version of Node 10 is required for execution.
A project that I am using this dependency in does not yet support Node 10, and it would simplify my build process greatly if the engine requirement was removed.
I've added the Node 8 version back to the Travis CI build to confirm that the runtime is valid.
> Downgrades Node runtime requirements to version 8

- package.json
- pegjs/mysql.pegjs
- src/util.js
- test/select.spec.js
- support table ref before column name
- support collate after json path
- fix issue #238
> support table ref, and collate for json path

- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/transactsql.pegjs
- src/command.js
- src/union.js
- test/cmd.spec.js
- support `drop procedure` in tsql #318 
- combine parse `drop` with `truncate` cmd to one function
> support tsql drop procedure, combine parse drop and truncate

- index.d.ts
- package.json
- pegjs/mysql.pegjs
- src/delete.js
- src/update.js
- test/delete.spec.js
- test/update.spec.js
- support `order by` and `limit` in delete and update SQL in MySQL #372 
- fix #366
> support order by and limit in update and delete sql

- pegjs/postgresql.pegjs
- test/create.spec.js
If I am not mistaken, `create table test(value unique key)` is NOT a valid postgres syntax... `create table test(value unique)` should be better.
This pull requests fixes it, and also fixes two tests which were using `expect()` directly in `describe()` statements, (not in `it()`)
> fix postgres unique index on table creation

- pegjs/postgresql.pegjs
- test/select.spec.js
- support quoted table and column name in pg #389
> support "table"."column" in pg column clause

- types.d.ts
Hi. `node-sql-parser` very awesome package! always thanks.
Duplicate identifier `Parser` class found in `types.d.ts`.
I think it should be removed because the current build failed.
> Remove duplicate identifier 'Parser'

- package.json
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- test/select.spec.js
- support `?` prepared statements in mysql
- support `$i` prepared statements in pg
- support #396
> support prepared statements in pg and mysql

- src/column.js
- src/util.js
- test/select.spec.js
Currently, output Postgresql / TSQL column aliases that contain special characters are wrapped in backticks. This is not valid SQL for either of these dialects; in Postgres the alias should be wrapped in double quotes, in TSQL the alias should be wrapped in either square brackets or double quotes.
Example of current behavior:
```js
const { Parser } = require('node-sql-parser');
const parser = new Parser()
const sqlInput = 'SELECT column_name AS "Column Name" FROM "table_name" as "Table Alias"';
const ast = parser.astify(sqlInput, { database: 'postgresql' });
const sqlOutput = parser.sqlify(ast, { database: 'postgresql'});
console.log(sqlOutput); // SELECT "column_name" AS `Column Name` FROM "table_name" AS "Table Alias"
```
In this PR I added a new function specific to column alias …
> Properly escape Postgres & TSQL column alias containing special characters

- types.d.ts
Hey!
Example query
```sql
SELECT
'Donor City' `donor__city`, count(`donor`._id) `donor__count`
FROM
Donors AS `donor`
GROUP BY 1 ORDER BY 2 DESC LIMIT 10000
```
Ast:
```
{
"with": null,
"type": "select",
"options": null,
"distinct": null,
"columns": [
{
"expr": {
"type": "string",
"value": "Donor City"
},
"as": "donor__city"
},
{
"expr": {
"type": "aggr_func",
"name": "COUNT",
"args": {
"distinct": null,
"expr": {
"type": "column_ref",
"table": "donor",
"column": "_id"
}
},
"over": null
},
"as": "donor__count"
}
],
"from": [
{
"db": null,
"table": "Donors",
"as": "donor"
}
],
"where": null,
"groupby": [
{
"type": "number",
"value": 1
}
],
"having": null,
"orderby": [
{
"expr": {
"type": "number",
"value": 2
},
"type": "DESC"
}
],
"limit": {
"seperator": "",
"value": [
{
"type": "number", …
```
> Fix(types): Select.limit field is an object, not an array

- pegjs/mysql.pegjs
- test/insert.spec.js
Hi, a query like this with different count between columns and rows will be successfully parsed:
```
INSERT INTO t1 (col1, col2, col3) values("1223", "name"), ("1224", "name2")
```
I have added a tentative correction.
> Unbalanced lengths between column count and row count

- pegjs/postgresql.pegjs
`type` is non-reserved in [`postgresql`](https://www.postgresql.org/docs/8.1/sql-keywords-appendix.html).
If you have a table with a column named `type` then the query:
```
SELECT id, type from my_table;
```
Fails to parse; however, this is valid SQL that Postgres processes correctly.
> Remove non-reserved Postgres type keyword

- pegjs/postgresql.pegjs
`interval` is not reserved in [postgres](https://www.postgresql.org/docs/8.1/sql-keywords-appendix.html). For example, `SELECT id, interval from table` is valid PostgreSQL but this library fails to parse it.
> Remove non-reserved interval keyword

- pegjs/mysql.pegjs
[In ECMAScript 5 strict mode code, duplicate property names were considered a SyntaxError.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#:~:text=In%20ECMAScript%205%20strict%20mode%20code%2C%20duplicate%20property%20names%20were%20considered%20a%20SyntaxError.)
> fix: remove duplicate key `CREATE`

- pegjs/hive.pegjs
- test/hive.spec.js
#857 does not parse "not rlike" as a valid value. In this commit I implemented it, added a test case.
> feat: support not rlike in hive

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> refactor: support function name with more dot in bigquery

- pegjs/postgresql.pegjs
- src/with.js
- test/ast.spec.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- test/select.spec.js
- related to #1090, escape with `cte` when sqlify
> refactor: escape with cte

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/select.js
- test/select.spec.js
Hi, mysql/maria DB implement locking reads:
Ref:
https://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html
https://mariadb.com/kb/en/select/
This PR adds support for it.
> Added support for mysql/mariadb locking read

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [`TRIM`](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/#string-functions) in Flink.
> feat: support trim in flink

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> fix: count distinct without parentheses in bigquery

- pegjs/mysql.pegjs
- src/column.js
- test/create.spec.js
Support generated fields per the [spec](https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html).
Fixes #1238.
> Support generated fields

- pegjs/mysql.pegjs
- src/column.js
- src/expr.js
- test/cmd.spec.js
- test/create.spec.js
Mysql [accepts `ASC` / `DESC` keywords for each column in the index](https://dev.mysql.com/doc/refman/8.0/en/descending-indexes.html), but the parser fails for those.
Also, the output of the `ALTER TABLE ... ADD KEY / INDEX` is invalid as it's using single quotes, while only backticks are allowed.
> Fix index with asc desc columns

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR removes `status` from the list of reserved keyword in Flink.
> feat: status as column name in flink

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for the [`IS [NOT] DISTINCT FROM` comparison function](https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/table/functions/systemfunctions/#comparison-functions).
> feat: support is distinct from in flink

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [the `LIKE` comparison operator with an `ESCAPE` character](https://calcite.apache.org/docs/reference.html#comparison-operators) in Flink.
> feat: support like with escape in flink

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [the `SIMILAR TO` comparison operator](https://calcite.apache.org/docs/reference.html#comparison-operators) in Flink.
> feat: support similar to in flink

- pegjs/flinksql.pegjs
- src/func.js
- test/flink.spec.js
This PR adds support for [`SUBSTRING`](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/#string-functions) in Flink.
> feat: support substring in flink

- src/parser.js
- src/sql.js
- test/ast.spec.js
- types.d.ts
This change allows us to constuct SQL expressions from AST fragments, which is really useful if, for example, you want to extract only the WHERE clause of an expression (very useful for generating RLS policies).
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>
> feat: Expose exprToSQL method to allow arbitray SQL construction

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [`TRY_CAST`](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/#type-conversion-functions) in Flink.
P.S.: would it be possible to also merge #1314, to minimize the conflicts?
> feat: support try_cast in flink

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [`POSITION`](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/#string-functions) in Flink.
> feat: support position in flink

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [`OVERLAY`](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/#string-functions) in Flink.
> feat: support overlay in flink

- pegjs/flinksql.pegjs
- test/flink.spec.js
This PR adds support for [all join operations](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/joins/) in Flink. See also [the relevant section of Calcite's Grammar](https://calcite.apache.org/docs/reference.html#grammar).
> feat: support all join operations in flink

- src/aggregation.js
- test/bigquery.spec.js
> fix: preserving double parenthesis in bigquery

- ast/postgresql.ts
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
- pegjs/sqlite.pegjs
- test/ast.spec.js
- test/flink.spec.js
- test/hive.spec.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
- test/select.spec.js
- test/sqlite.spec.js
Hi maintainers, I fixed https://github.com/taozhi8833998/node-sql-parser/issues/1537
Changed to pegjs file to support union distinct on below databases (I supported only databases where documents could be found)
- [db2](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statement-combining-result-tables-from-multiple-select-statements#taskdb2z_combineresultmultipleselect__context__1)
- [flinksql](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/hive-compatibility/hive-dialect/queries/set-op/#union)
- [hive](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Union)
- [mariadb](https://mariadb.com/kb/en/union/)
- [mysql](https://dev.mysql.com/doc/refman/8.0/en/union.html)
- [postgresql](https://www.postgresql.org/docs/current/sql-select.html)
- sqlite …
> Support union distinct on various databases

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> feat: support accentuated characters in pg

- pegjs/mysql.pegjs
Incorrect handling of assignment statements in the column list on select queries.
> select requires := for assignment, otherwise its a binary operator

- pegjs/mysql.pegjs
select db.table.column from db.table is valid syntax in mysql.
> allow db prefix in column_refs

- pegjs/transactsql.pegjs
- src/exec.js
- test/transactsql.spec.js
- feat: support exec statement without execute parameters
- fix: fix the problem which causes 'execute' keyword cannot be recognized
> feat: support exec stmt without parameters

- pegjs/bigquery.pegjs
- src/create.js
- src/tables.js
- test/bigquery.spec.js
> feat: support create table in bigquery

- ast/postgresql.ts
- pegjs/mysql.pegjs
- pegjs/postgresql.pegjs
Fixes unary `-`, `+`, `!` and `~` precedence rules.
> fix unary operation

- pegjs/mysql.pegjs
Support `ALTER TABLE table_name DROP INDEX index_name` and `ALTER TABLE table_name DROP KEY index_name`
> drop index support in alter command

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
> feat: support string_agg function in bigquery

- index.js
This PR aims to use the `typeof` keyword to make it working with browsers.
Using `!global` in browser would make crash as `global` object is not defined in browsers.
> Use typeof comparaison on global object for browsers usage

- .github/workflows/npm-publish-github-packages.yml
- fix registry.npm.taobao.org cert expired, change to registry.npmmirror.com, disable ssl check temporarily
> refactor: registry.npm.taobao.org cert expired

- pegjs/snowflake.pegjs
- test/snowflake.spec.js
Snowflake has REGEXP / NOT REGEXP but lacks ~ and ! ~
This PR adjusts the syntax accordingly
https://docs.snowflake.com/en/sql-reference/functions/regexp
Fixes: https://github.com/taozhi8833998/node-sql-parser/issues/1823
> fix(snowflake): support the REGEXP / NOT REGEXP operator

- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- src/column.js
- src/func.js
- test/cmd.spec.js
- test/select.spec.js
- test/update.spec.js
- change function name from string type to object, keep original quoted symbol
> refactor: change all function with all quoted object

- types.d.ts
This is a re-introduction of  the changes made in https://github.com/taozhi8833998/node-sql-parser/pull/1828
The PR above was made to the upstream [refactor-quoted-func-name](https://github.com/taozhi8833998/node-sql-parser/tree/refactor-quoted-func-name) branch, but the branch was merged to master before https://github.com/taozhi8833998/node-sql-parser/pull/1828 was merged - so the types were not updated in master
I now submitted this PR to master
> refactor: new function name types

- pegjs/bigquery.pegjs
- test/bigquery.spec.js
In BigQuery dialect, everything in parentheses is considered as `type: 'array'`. 
This PR fixes this behavior to distinguish between brackets (`[]`) which are indeed considered as array, and parentheses which require an explicit `array(...)` expression
Fixing this changed the behavior of multiple parentheses expression, when reconstructing the sql from ast. This caused a test to fail, which was added when fixing [this issue](https://github.com/taozhi8833998/node-sql-parser/issues/1661) . We changed the test to accommodate the new behavior. The issue talked about a syntactic error (`((...))` turned to `[(...)]` which is wrong), while the new behavior simply omits the redundant parentheses (`((...))` turning to `(...)` which are syntactically equivalent)
> fix: bigquery array brackets and parentheses handling

- ast/postgresql.ts
- pegjs/athena.pegjs
- pegjs/bigquery.pegjs
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/hive.pegjs
- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/transactsql.pegjs
- pegjs/trino.pegjs
- src/command.js
- test/mysql-mariadb.spec.js
> feat: support multiple set items in mysql

- types.d.ts
In BigQuery and mysql, the alias can be wrapped with backticks and then the as evaluates as ValueExpr<string> with type "backticks_quote_string"
> Support Column "as" to be ValueExpr

- types.d.ts
It appears that `Expr` represents a binary expression used in a condition, and in the `Cast` node, it seems more appropriate to use `ExpressionValue` instead of `Expr`. 
I dump the AST and found that the `expr` in the `Cast` node is indeed `ExpressionValue` not `Expr`:
```json
"expr": {
"type": "cast",
"keyword": "cast",
"expr": {
"type": "column_ref",
"table": null,
"column": "out_trade_no_"
},
"symbol": "as",
"target": {
"dataType": "INTEGER",
"suffix": []
}
},
```
> Change the type definition of `Cast.expr` from `Expr` to `ExpressionValue`

- ast/postgresql.ts
- pegjs/db2.pegjs
- pegjs/flinksql.pegjs
- pegjs/mysql.pegjs
- pegjs/noql.pegjs
- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/snowflake.pegjs
- pegjs/sqlite.pegjs
- pegjs/trino.pegjs
- src/column.js
- src/expr.js
- src/func.js
- test/mysql-mariadb.spec.js
- test/postgres.spec.js
> Feat jsonb operator pg

- pegjs/snowflake.pegjs
- src/create.js
- test/snowflake.spec.js
> fix: create or replace view in snowflake

- pegjs/postgresql.pegjs
- test/postgres.spec.js
> fix: create table as table defintion could be optional in pg

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- test/mysql-mariadb.spec.js
> fix: convert function with expr in mysql

- types.d.ts
This PR modifies and simplifies the definition of the binary expression type, which I've renamed `Expr` -> `Binary` for clarity. I've made binary expressions a valid `ExpressionValue`, since I don't see why it's treated separately from all other expressions. If there's a compelling reason I'm not seeing, let me know! For historical context, this type definition was introduced by #1675.
Resolves #2157
> Make Binary expression type def more flexible

- pegjs/athena.pegjs
- test/athena.spec.js
> fix: key as column in athena

- pegjs/mariadb.pegjs
- src/alter.js
- test/cmd.spec.js
- test/mysql-mariadb.spec.js
I'm not sure if you accept contributions, however I've had a go at fixing an issue I reported. As far as I know `FIRST <column>` is not valid in any flavour of SQL, unlike `AFTER <column>`.
resolves #2232
> fix: don't require column expression for alter first

- pegjs/postgresql.pegjs
- pegjs/redshift.pegjs
- pegjs/trino.pegjs
- test/postgres.spec.js
> fix: column list include function name

- pegjs/mysql.pegjs
- test/cmd.spec.js
This PR adds support for `ALTER TABLE foo DROP CONSTRAINT bar` syntax. 
This is supported in MySQL 8.0 onwards (https://dev.mysql.com/doc/refman/8.0/en/alter-table.html)
> fix: support drop constraint in mysql

- pegjs/mariadb.pegjs
- pegjs/mysql.pegjs
- src/tables.js
- test/mysql-mariadb.spec.js
> refactor: support join after parentheses in mysql

- ast/postgresql.ts
> refactor: update type definition

- ast/postgresql.ts
- pegjs/postgresql.pegjs
- test/postgres.spec.js
`DELETE` statements support including the `RETURNING` clause in a the same way as `UPDATE` / `INSERT` statements do.
ref: https://www.postgresql.org/docs/current/sql-delete.html
> feat(postgres): support delete returning queries

- pegjs/sqlite.pegjs
- test/sqlite.spec.js
adds the `RETURNING` statement to the sqlite grammer. copies the approach from the postgres grammer.
references:
- https://sqlite.org/syntax/returning-clause.html
- https://sqlite.org/lang_returning.html
> feat(sqlite): support returning on insert, update and delete

- pegjs/athena.pegjs
- test/athena.spec.js
> feat: add boolean type in athena

- types.d.ts
Hi there,
For the literal value datatype such as `ENUM('one', 'two')` the parser emits
```json
"definition": {
"dataType": "ENUM",
"expr": { "type": "expr_list", value: [...] }
}
```
But DataType in `types.d.ts` file omits `expr` property, so downstream TypeScript code that inspects the AST can’t be typed correctly.
Hope we can fix this
> fix(types): add expr to DataType

- types.d.ts
Hi there,
When parsing the SQL statements that define indexes, the AST includes the `order_by` property on ColumnRefItem objects. For example:
```json
"definition": [
{
"type": "column_ref",
"column": "email",
"order_by": "ASC"
}
],
```
However the ColumnRefItem interface does not currently include `order_by`, which causes type errors when working with the returned AST.
Thanks for maintaining this repo.
> fix(types) add order_by to ColumnRefItem

- types.d.ts
This improves the typings a bit, in particular for the `CREATE INDEX` statement. I'm basing this off of the behavior I'm seeing for the following SQL using the SQLite dialect:
```sql
CREATE INDEX person_idx ON persons (name DESC) where name is not null
```
```json
{
"type": "create",
"index_type": null,
"keyword": "index",
"if_not_exists": null,
"index": {
"schema": null,
"name": "person_idx"
},
"on_kw": "on",
"table": {
"db": null,
"table": "persons"
},
"index_columns": [
{
"collate": null,
"type": "column_ref",
"table": null,
"column": "name",
"order_by": "desc"
}
],
"where": {
"type": "binary_expr",
"operator": "IS NOT",
"left": {
"type": "column_ref",
"table": null,
"column": "name",
"collate": null
},
"right": {
"type": "null",
"value": null
}
}
}
```
> fix: improve types for `CREATE INDEX`

- pegjs/trino.pegjs
- src/array-struct.js
- test/trino.spec.js
Enables correct parsing of trino statements like `SELECT ROW(12 AS x, 122 y) FROM t`
> Support ROW expressions in trino

- ast/postgresql.ts
- pegjs/postgresql.pegjs
> fix: build error when missing insert_value_clause types in pg
